language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.1.4
      mono: none
    - os: osx
      osx_image: xcode9.3
      dotnet: 2.1.4
      mono: none

branches:
  only:
    - master

script:
  - sed -i -e 's/net20;net40;net45;//' ./src/Pkcs11Interop/Pkcs11Interop.csproj
  - sed -i -e 's/net20;net40;net45;//' ./src/Pkcs11Interop.Mock/Pkcs11Interop.Mock.csproj
  - sed -i -e 's/net20;net40;net45;//' ./src/Pkcs11Interop.Tests/Pkcs11Interop.Tests.csproj
  - dotnet --info
  - dotnet restore ./src/
  - dotnet build ./src/
  - dotnet test -f netcoreapp2.0 ./src/Pkcs11Interop.Tests/
