language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.1.4
      mono: none
    - os: osx
      osx_image: xcode9.3
      dotnet: 2.1.4
      mono: none

branches:
  only:
    - master

script:
  - dotnet --info
  - dotnet restore ./src/Pkcs11Interop.NetStandard/
  - dotnet build ./src/Pkcs11Interop.NetStandard/
  - dotnet test -f netcoreapp2.0 ./src/Pkcs11Interop.NetStandard/Pkcs11Interop.DotNetCore.Tests/
